[build]
  command = "gatsby build"
  publish = "public/"

[template]
  incoming-hooks = ["Ghost"]

[[redirects]]
    from = "/ghost"
    to = "https://hackersandslackers.app/ghost"
    status = 301
    force = true

[[redirects]]
    from = "/wp-login.php"
    to = "https://i.imgur.com/1Ia9tTG.gif"
    status = 301

[[redirects]]
    from = "/structuring-your-flask-app/"
    to = "/organizing-flask-with-blueprints"
    status = 301

[[redirects]]
    from = "/liberating-data-from-pdfs-with-tabula-and-pandas/"
    to = "/liberating-data-from-pdfs-with-tabula-and-pandas/"
    status = 301

[[redirects]]
    from = "/lets-start-with-perhaps-the-most-useful-vb-script-youll-ever-run-out-of-excel/"
    to = "/excel-data-manipulation-for-everyone/"
    status = 301

[[redirects]]
    from = "/how-i-learned-to-stop-worry/"
    to = "/learning-to-love-excel-formulas/"
    status = 301

[[redirects]]
    from = "/index-match-vs-the-lookups-an-excel-soujurn/"
    to = "/excel-index-match-vs-lookups/"
    status = 301

[[redirects]]
    from = "/the-one-formula-to-rule-them-all-adventures-in-excel/"
    to = "/the-one-excel-formula-to-rule-them-all/"
    status = 301

[[redirects]]
    from = "/pivoting-not-just-for-startups-anymore-adventures-in-excel/"
    to = "/the-art-of-excel-pivot-tables/"
    status = 301

[[redirects]]
    from = "/powering-up-your-pivot/"
    to = "/powering-up-your-excel-pivot-tables/"
    status = 301

[[redirects]]
    from = "/roll-on-through-create-an-expanding-list-without-vba/"
    to = "/create-an-iterative-list-in-excel/"
    status = 301

[[redirects]]
    from = "/dynamic-tension-creating-and-using-dynamic-named-ranges/"
    to = "/dynamic-named-ranges-in-excel/"
    status = 301

[[redirects]]
    from = "/named-ranges-and-the-active-xs-who-love-them/"
    to = "/excel-named-ranges-and-the-active-xs-who-love-them/"
    status = 301

[[redirects]]
    from = "/pivot-party-adventures-in-excel/"
    to = "/excel-pivot-table-party/"
    status = 301

[[redirects]]
    from = "/the-way-of-the-knife/"
    to = "/slicing-excel-the-way-of-the-knife/"
    status = 301

[[redirects]]
    from = "/yes-and-if-or-adventures-in-excel/"
    to = "/excels-mighty-if-statement/"
    status = 301

[[redirects]]
    from = "/getting-if-fy-with-it-adventures-in-excel/"
    to = "/dirty-data-in-excel-part-2/"
    status = 301

[[redirects]]
    from = "/dealing-with-dirty-data-adventures-in-excel-2/"
    to = "/dealing-with-dirty-data-in-excel/"
    status = 301

[[redirects]]
    from = "/dealing-with-dirty-data-adventures-in-excel/"
    to = "/doing-the-excel-data-dance/"
    status = 301

[[redirects]]
    from = "/powering-up-your-pivot/"
    to = "/powering-up-your-excel-pivot-tables/"
    status = 301

[[redirects]]
    from = "/creating-endpoints-with-lambda/"
    to = "/create-a-rest-api-endpoint-using-aws-lambda/"
    status = 301

[[redirects]]
    from = "/tag/aws-api/"
    to = "/series/create-an-aws-api/"
    status = 301

[[redirects]]
    from = "/hacking-linux-tableu-server/"
    to = "/hacking-linux-tableau-server/"
    status = 301

[[redirects]]
    from = "/products/mongodb-enterprise-advanced/"
    to = "/series/mongodb-cloud/"
    status = 301

[[redirects]]
    from = "/starting-a-flask-project-with-heroku/"
    to = "/starting-a-python-web-app-with-heroku/"
    status = 301

[[redirects]]
    from = "/data-could-solve-humanitys-greatest-problems-if-it-werent-for-humanity/"
    to = "/data-could-save-humanity/"
    status = 301

[[redirects]]
    from = "/tuning-random-forests-hyperparameters-with-binary-search-part-iii-min_samples_leaf/"
    to = "/random-forests-hyperparameters-min_samples_leaf/"
    status = 301

[[redirects]]
    from = "/using-random-forests-for-feature-selection-with-categorical-features/"
    to = "/random-forests-for-feature-selection/"
    status = 301

[[redirects]]
    from = "/code-snippet-corner-getting-conda-envs-and-environment-variables-to-play-nicely-with-cron/"
    to = "/conda-environments-and-cron/"
    status = 301

[[redirects]]
    from = "/code-snippet-corner-tuning-machine-learning-hyperparameters-with-binary-search/"
    to = "/tuning-machine-learning-hyperparameters-with-binary-search/"
    status = 301

[[redirects]]
    from = "/api/handlebars-themes/"
    to = "/handlebars-templating-in-expressjs"
    status = 301

[[redirects]]
    from = "/tag/aws-api/"
    to = "/series/create-an-aws-api/"
    status = 301

[[redirects]]
    from = "/creating-endpoints-with-lambda/"
    to = "/create-a-rest-api-endpoint-using-aws-lambda/"
    status = 301

[[redirects]]
    from = "/pipenv-etc-tracking-your-projects-dependancies/"
    to = "/pipenv-python-environment-management/"
    status = 301

[[redirects]]
    from = "/demystifying-flasks-application-context/"
    to = "/demystifying-flask-application-factory/"
    status = 301

[[redirects]]
    from = "/structuring-your-flask-app/"
    to = "/demystifying-flask-application-factory/"
    status = 301

[[redirects]]
    from = "accessing-mysql-from-external-domains/"
    to = "/accessing-mysql-externally/"
    status = 301

[[redirects]]
    from = "/sqlalchemy-managing-relationships-data-models/"
    to = "/sqlalchemy-data-models/"
    status = 301

[[redirects]]
    from = "/constructuing-database-queries-with-the-sqlalchemy-orm/"
    to = "/database-queries-sqlalchemy-orm/"
    status = 301

[[redirects]]
    from = "/python-database-management-with-sqlalchemy/"
    to = "/python-database-management-with-sqlalchemy/"
    status = 301

[[redirects]]
    from = "/comparing-rows-between-two-pandas-dataframes/"
    to = "/compare-rows-pandas-dataframes/"
    status = 301

[[redirects]]
    from = "/dataframe-transformations-in-pyspark-continued/"
    to = "/transforming-pyspark-dataframes/"
    status = 301

[[redirects]]
    from = "/basic-dataframe-transformations-in-pyspark/"
    to = "/transforming-pyspark-dataframes/"
    status = 301

[[redirects]]
    from = "/selecting-data-from-pyspark-dataframes/"
    to = "/transforming-pyspark-dataframes/"
    status = 301

[[redirects]]
    from = "/pyspark-macro-dataframe-methods-join-and-groupby/"
    to = "/join-aggregate-pyspark-dataframes/"
    status = 301

[[redirects]]
    from = "/manage-s3-assests-with-boto3-python-sdk/"
    to = "/s3-boto3-python-sdk/"
    status = 301

[[redirects]]
    from = "/reading-and-writing-to-csvs-in-python/"
    to = "/read-write-csv-python/"
    status = 301


[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

    # Multi-key header rules are expressed with multi-line strings.
    cache-control = '''
      max-age=31557600,
      no-cache,
      no-store,
      must-revalidate'''
      set-cookie = "HttpOnly;Secure;SameSite=Strict"

[[headers]]
    for = "https://gaug.es/*"
    [headers.values]
      cache-control = '''
        max-age=31557600,
        no-cache,
        no-store,
        must-revalidate'''
      set-cookie = "HttpOnly;Secure;SameSite=Strict"

[[headers]]
    for = "http://secure.gaug.es/*"
    [headers.values]
      cache-control = '''
        max-age=31557600,
        no-cache,
        no-store,
        must-revalidate'''
      set-cookie = "HttpOnly;Secure;SameSite=Strict"

[[headers]]
    for = "http://get.gaug.es/*"
    [headers.values]
      cache-control = '''
        max-age=31557600,
        no-cache,
        no-store,
        must-revalidate'''
      set-cookie = "HttpOnly;Secure;SameSite=Strict"

[[headers]]
    for = "https://cloudinary.com/*"
    [headers.values]
    cache-control = '''
        max-age=31557600,
        no-cache,
        no-store,
        must-revalidate'''
    set-cookie = "HttpOnly;Secure;SameSite=Strict"


[[headers]]
    for = "https://res-1.cloudinary.com/*"
    [headers.values]
    cache-control = '''
            max-age=31557600,
            no-cache,
            no-store,
            must-revalidate'''
    set-cookie = "HttpOnly;Secure;SameSite=Strict"

[[headers]]
    for = "https://res-2.cloudinary.com/*"
    [headers.values]
    cache-control = '''
            max-age=31557600,
            no-cache,
            no-store,
            must-revalidate'''
    set-cookie = "HttpOnly;Secure;SameSite=Strict"

[[headers]]
    for = "https://segment.com/*"
    [headers.values]
    cache-control = '''
            max-age=31557600,
            no-cache,
            no-store,
            must-revalidate'''
    set-cookie = "HttpOnly;Secure;SameSite=Strict"

[[headers]]
    for = "https://app.segment.com/"
    [headers.values]
    cache-control = '''
            max-age=31557600,
            no-cache,
            no-store,
            must-revalidate'''
    set-cookie = "HttpOnly;Secure;SameSite=Strict"

[[headers]]
    for = "https://cdn.segment.com/*"
    [headers.values]
    cache-control = '''
            max-age=31557600,
            no-cache,
            no-store,
            must-revalidate'''
    set-cookie = "HttpOnly;Secure;SameSite=Strict"

[[headers]]
      for = "https://storage.googleapis.com/*"
      [headers.values]
      cache-control = '''
              max-age=31557600,
              no-cache,
              no-store,
              must-revalidate'''
      set-cookie = "HttpOnly;Secure;SameSite=Strict"

[[headers]]
    for = "https://hello.myfonts.net/*"
    [headers.values]
    cache-control = '''
        max-age=31557600,
        no-cache,
        no-store,
        must-revalidate'''
    set-cookie = "HttpOnly;Secure;SameSite=Strict"

[[headers]]
    for = "https://myfonts.net/*"
    [headers.values]
    cache-control = '''
        max-age=31557600,
        no-cache,
        no-store,
        must-revalidate'''
    set-cookie = "HttpOnly;Secure;SameSite=Strict"


[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true
